In [1]:
import torch
import torch.nn as nn
import numpy as np

In [2]:
x1 = torch.tensor([1,2,3,4,5], dtype=torch.float32, requires_grad=False).reshape(-1,1)
x2 = x1 * 10
print(x1)
print(x2)

tensor([[1.],
        [2.],
        [3.],
        [4.],
        [5.]])
tensor([[10.],
        [20.],
        [30.],
        [40.],
        [50.]])


In [22]:
model = nn.BatchNorm1d(1)
# for module in model.modules():
#     if isinstance(module, nn.BatchNorm1d):
#         print("found batchnorm instance.")
#         module.track_running_stats = False

# model.eval()

In [17]:
y2 = model(x2)
print(y2)
print(next(iter(model.modules())).running_mean)
print(next(iter(model.modules())).running_var)

tensor([[-1.4142],
        [-0.7071],
        [ 0.0000],
        [ 0.7071],
        [ 1.4142]], grad_fn=<NativeBatchNormBackward0>)
tensor([3.])
tensor([25.9000])


In [23]:
y1 = model(x1)
print(y1)
print(next(iter(model.modules())).running_mean)
print(next(iter(model.modules())).running_var)

# model.eval()

for module in model.modules():
    if isinstance(module, nn.BatchNorm1d):
        # print("found batchnorm instance.")
        # module.track_running_stats = False
        module.reset_running_stats()
    else:
        for param in module.parameters():
            param.requires_grad_(False)
        module.eval()

y2 = model(x2)
print(y2)
print(next(iter(model.modules())).running_mean)
print(next(iter(model.modules())).running_var)

tensor([[-1.4142],
        [-0.7071],
        [ 0.0000],
        [ 0.7071],
        [ 1.4142]], grad_fn=<NativeBatchNormBackward0>)
tensor([0.3000])
tensor([1.1500])
tensor([[-1.4142],
        [-0.7071],
        [ 0.0000],
        [ 0.7071],
        [ 1.4142]], grad_fn=<NativeBatchNormBackward0>)
tensor([3.])
tensor([25.9000])


In [ ]:
print(next(iter(model.modules())).running_var)

In [ ]:
for module in model.modules():
    if isinstance(module, nn.BatchNorm1d):
        module.track_running_stats = False
    else:
        for param in module.parameters():
            param.requires_grad = False
        module.eval()

In [ ]:
y2 = model(x2)
print(y2)
print(next(iter(model.modules())).running_mean)